// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlSn-_Qt2YqWa4SYDsxMHWpDR6aNj3Edo',
    appId: '1:809659828182:web:b4134c205c01acc74a4677',
    messagingSenderId: '809659828182',
    projectId: 'ederine-5fb65',
    authDomain: 'ederine-5fb65.firebaseapp.com',
    storageBucket: 'ederine-5fb65.firebasestorage.app',
    measurementId: 'G-JHB12X0PYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT-loV8ypHf_ZEg96vdhuZdsEIVkV-hlc',
    appId: '1:809659828182:android:1d1ba19885875a434a4677',
    messagingSenderId: '809659828182',
    projectId: 'ederine-5fb65',
    storageBucket: 'ederine-5fb65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKVHGiYP_7fOUgBW8tYL3ASiNaS_YXtU',
    appId: '1:809659828182:ios:2a6c017a7ed9c6924a4677',
    messagingSenderId: '809659828182',
    projectId: 'ederine-5fb65',
    storageBucket: 'ederine-5fb65.firebasestorage.app',
    iosBundleId: 'com.example.ederineV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKVHGiYP_7fOUgBW8tYL3ASiNaS_YXtU',
    appId: '1:809659828182:ios:2a6c017a7ed9c6924a4677',
    messagingSenderId: '809659828182',
    projectId: 'ederine-5fb65',
    storageBucket: 'ederine-5fb65.firebasestorage.app',
    iosBundleId: 'com.example.ederineV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlSn-_Qt2YqWa4SYDsxMHWpDR6aNj3Edo',
    appId: '1:809659828182:web:ef15de0c8b4ce9b34a4677',
    messagingSenderId: '809659828182',
    projectId: 'ederine-5fb65',
    authDomain: 'ederine-5fb65.firebaseapp.com',
    storageBucket: 'ederine-5fb65.firebasestorage.app',
    measurementId: 'G-H9WPDVX0VF',
  );
}
